# =============================================================
# NEKOVA Package Manager — CLI Interface
# =============================================================
# Handles all package management commands:
#   python main.py --install <package>
#   python main.py --uninstall <package>
#   python main.py --packages
#
# Architecture:
#   - Looks up package in BUILTIN_PACKAGES registry
#   - Installs it by creating a module file in packages/
#   - Updates registry.json to track installed packages
#   - Makes it available via "use <package>" in NEKOVA code

import os
import json
from config import Color
from cli import print_success, print_error, print_info, print_warning
from packages import (
    BUILTIN_PACKAGES, load_registry, save_registry,
    is_installed, PACKAGES_DIR
)


def install_package(name: str) -> bool:
    """
    Install a package by name.
    Returns True if successful, False otherwise.
    """
    print_info(f"Installing '{name}'...")

    # Check if already installed
    if is_installed(name):
        print_warning(f"'{name}' is already installed.")
        return True

    # Check if package exists
    if name not in BUILTIN_PACKAGES:
        available = ", ".join(BUILTIN_PACKAGES.keys())
        print_error(
            f"Package '{name}' was not found.\n"
            f"  Available packages: {available}"
        )
        return False

    package = BUILTIN_PACKAGES[name]

    # Generate the package module file
    success = _create_package_module(name, package)
    if not success:
        return False

    # Update registry
    registry = load_registry()
    registry[name] = {
        "name":        package["name"],
        "version":     package["version"],
        "description": package["description"],
        "installed":   True,
    }
    save_registry(registry)

    print_success(
        f"Installed '{name}' v{package['version']} — "
        f"{package['description']}"
    )
    print_info(f"Use it in NEKOVA with:  use {name}")
    return True


def uninstall_package(name: str) -> bool:
    """
    Uninstall a package by name.
    Returns True if successful, False otherwise.
    """
    if not is_installed(name):
        print_error(f"'{name}' is not installed.")
        return False

    # Remove module file
    module_path = os.path.join(PACKAGES_DIR, f"{name}.py")
    if os.path.exists(module_path):
        os.remove(module_path)

    # Update registry
    registry = load_registry()
    del registry[name]
    save_registry(registry)

    print_success(f"Uninstalled '{name}' successfully.")
    return True


def list_packages():
    """Display all available and installed packages."""
    installed = load_registry()
    available = BUILTIN_PACKAGES

    print()
    print(f"{Color.CYAN}{Color.BOLD}  NEKOVA Package Registry{Color.RESET}")
    print(f"  {Color.DIM}{'─' * 44}{Color.RESET}")

    for name, info in available.items():
        is_inst  = name in installed
        status   = (f"{Color.GREEN}✓ installed{Color.RESET}"
                    if is_inst else
                    f"{Color.DIM}  available{Color.RESET}")
        version  = info["version"]
        desc     = info["description"]

        print(f"  {Color.BOLD}{name:<16}{Color.RESET}"
              f"{Color.DIM}v{version:<8}{Color.RESET}"
              f"{status}")
        print(f"  {Color.DIM}{'':16}{desc}{Color.RESET}")
        print()

    total     = len(available)
    inst_count = len(installed)
    print(f"  {Color.DIM}{inst_count}/{total} packages installed{Color.RESET}")
    print()


def _create_package_module(name: str, package: dict) -> bool:
    """
    Generate a Python module file for the package
    inside the packages/ directory.
    """
    module_path = os.path.join(PACKAGES_DIR, f"{name}.py")

    try:
        content = _generate_module_code(name, package)
        with open(module_path, "w", encoding="utf-8") as f:
            f.write(content)
        return True

    except Exception as e:
        print_error(f"Failed to create package module: {e}")
        return False


def _generate_module_code(name: str, package: dict) -> str:
    """Generate the Python code for a package module."""

    generators = {
        "charts":     _charts_module,
        "auth":       _auth_module,
        "validation": _validation_module,
        "colors":     _colors_module,
        "random":     _random_module,
    }

    generator = generators.get(name)
    if generator:
        return generator()

    # Generic fallback
    return f'''# NEKOVA Package — {name}
# Auto-generated by NEKOVA Package Manager

def load() -> dict:
    return {{}}
'''


# ── Package module generators ─────────────────────────────────

def _charts_module() -> str:
    return '''# NEKOVA Package — charts
# Simple ASCII charts for terminal output

def load() -> dict:
    return {
        "bar_chart":  _bar_chart,
        "line_chart": _line_chart,
        "pie_chart":  _pie_chart,
    }

def _bar_chart(data: list, width: int = 20):
    if not data: return ""
    max_val = max(data) if max(data) > 0 else 1
    lines = []
    for i, val in enumerate(data):
        bar_len = int((val / max_val) * width)
        bar     = "#" * bar_len
        lines.append(f"  {i+1:>2} | {bar} {val}")
    return "\\n".join(lines)

def _line_chart(data: list, width: int = 40):
    if not data: return ""
    max_val = max(data) if max(data) > 0 else 1
    min_val = min(data)
    height  = 10
    lines   = []
    for row in range(height, -1, -1):
        line = ""
        for val in data:
            normalized = (val - min_val) / (max_val - min_val + 0.001)
            if int(normalized * height) >= row:
                line += "o"
            else:
                line += " "
        lines.append(f"  |{line}")
    lines.append(f"  +{-len(data) * -1 * chr(45)}")
    return "\\n".join(lines)

def _pie_chart(data: dict):
    if not data: return ""
    total = sum(data.values())
    lines = ["  Pie Chart:"]
    for label, val in data.items():
        pct     = (val / total) * 100 if total > 0 else 0
        bar_len = int(pct / 5)
        bar     = "#" * bar_len
        lines.append(f"  {label:<12} | {bar} {pct:.1f}%")
    return "\\n".join(lines)
'''


def _auth_module() -> str:
    return '''# NEKOVA Package — auth
# Basic authentication utilities

import hashlib
import secrets

def load() -> dict:
    return {
        "hash_password":    _hash_password,
        "check_password":   _check_password,
        "generate_token":   _generate_token,
    }

def _hash_password(password: str) -> str:
    salt   = secrets.token_hex(16)
    hashed = hashlib.sha256(
        (salt + str(password)).encode()
    ).hexdigest()
    return f"{salt}:{hashed}"

def _check_password(password: str, hashed: str) -> bool:
    try:
        salt, hash_val = hashed.split(":")
        check = hashlib.sha256(
            (salt + str(password)).encode()
        ).hexdigest()
        return check == hash_val
    except Exception:
        return False

def _generate_token(length: int = 32) -> str:
    return secrets.token_hex(int(length))
'''


def _validation_module() -> str:
    return '''# NEKOVA Package — validation
# Input validation helpers

import re

def load() -> dict:
    return {
        "is_email":           _is_email,
        "is_phone":           _is_phone,
        "is_url":             _is_url,
        "is_strong_password": _is_strong_password,
    }

def _is_email(value: str) -> bool:
    pattern = r"^[a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\\.[a-zA-Z0-9-.]+$"
    return bool(re.match(pattern, str(value)))

def _is_phone(value: str) -> bool:
    pattern = r"^\\+?[0-9]{7,15}$"
    return bool(re.match(pattern, str(value).replace(" ", "")))

def _is_url(value: str) -> bool:
    pattern = r"^https?://[^\\s/$.?#].[^\\s]*$"
    return bool(re.match(pattern, str(value)))

def _is_strong_password(value: str) -> bool:
    s = str(value)
    return (len(s) >= 8 and
            any(c.isupper() for c in s) and
            any(c.islower() for c in s) and
            any(c.isdigit() for c in s))
'''


def _colors_module() -> str:
    return '''# NEKOVA Package — colors
# Terminal color utilities

def load() -> dict:
    return {
        "red":    lambda t: f"\\033[91m{t}\\033[0m",
        "green":  lambda t: f"\\033[92m{t}\\033[0m",
        "yellow": lambda t: f"\\033[93m{t}\\033[0m",
        "blue":   lambda t: f"\\033[94m{t}\\033[0m",
        "bold":   lambda t: f"\\033[1m{t}\\033[0m",
        "dim":    lambda t: f"\\033[2m{t}\\033[0m",
    }
'''


def _random_module() -> str:
    return '''# NEKOVA Package — random
# Random value generation

import importlib
import sys

# Force load Python's built-in random, not this file
_random = importlib.import_module("random")

def load() -> dict:
    return {
        "random_int":    lambda a, b: _random.randint(int(a), int(b)),
        "random_float":  lambda a, b: _random.uniform(float(a), float(b)),
        "random_choice": lambda lst: _random.choice(lst),
        "shuffle":       lambda lst: _random.sample(lst, len(lst)),
        "random_token":  lambda n=8: "".join(
            _random.choices("abcdefghijklmnopqrstuvwxyz0123456789",
                           k=int(n))),
    }
'''