# =============================================================
# NEKOVA Deploy — App Bundler
# =============================================================
# Packages an NEKOVA app into a self-contained deployment bundle.
# The bundle includes everything needed to run the app
# on any server without NEKOVA pre-installed.
#
# Usage:
#   from deploy.bundle import AppBundler
#   bundler = AppBundler()
#   bundle_dir = bundler.bundle("examples/web_demo.aion")

import os
import shutil
import tempfile


class AppBundler:
    """
    Creates a self-contained deployment bundle from an NEKOVA app.
    """

    def bundle(self, filepath: str) -> str:
        """
        Bundle an NEKOVA app into a temp directory.
        Returns the path to the bundle directory.
        """
        app_name = os.path.splitext(
            os.path.basename(filepath))[0]

        # Create temp bundle directory
        bundle_dir = tempfile.mkdtemp(
            prefix=f"aion_{app_name}_")

        print(f"  → Copying app files...")
        self._copy_app(filepath, bundle_dir, app_name)

        print(f"  → Writing runtime files...")
        self._write_requirements(bundle_dir)
        self._write_procfile(bundle_dir, app_name)
        self._write_main(bundle_dir, app_name)
        self._write_readme(bundle_dir, app_name)
        self._write_railway_config(bundle_dir, app_name)

        print(f"  → Bundle ready: {bundle_dir}")
        return bundle_dir

    def _copy_app(self, filepath: str,
                  bundle_dir: str, app_name: str):
        """Copy the NEKOVA source file to the bundle."""
        dest = os.path.join(bundle_dir, f"{app_name}.aion")
        shutil.copy2(filepath, dest)

        # Copy NEKOVA core modules needed at runtime
        aion_root = os.path.dirname(
            os.path.dirname(os.path.abspath(__file__))
        )

        core_dirs = [
            "lexer", "parser", "interpreter",
            "runtime", "stdlib", "ai", "compiler",
            "web", "database", "ui"
        ]

        for dir_name in core_dirs:
            src = os.path.join(aion_root, dir_name)
            dst = os.path.join(bundle_dir, dir_name)
            if os.path.isdir(src):
                shutil.copytree(src, dst,
                    ignore=shutil.ignore_patterns(
                        "__pycache__", "*.pyc"))

        # Copy config.py and runner.py
        for fname in ["config.py", "runner.py"]:
            src = os.path.join(aion_root, fname)
            if os.path.isfile(src):
                shutil.copy2(src,
                    os.path.join(bundle_dir, fname))

    def _write_requirements(self, bundle_dir: str):
        """Write requirements.txt for the bundle."""
        requirements = """flask>=2.0.0
google-genai>=2.0.0
colorama>=0.4.0
python-dotenv>=0.19.0
requests>=2.27.0
"""
        path = os.path.join(bundle_dir, "requirements.txt")
        with open(path, "w") as f:
            f.write(requirements)

    def _write_procfile(self, bundle_dir: str,
                        app_name: str):
        """Write Procfile for Railway/Heroku."""
        content = f"web: python main.py {app_name}.aion\n"
        path = os.path.join(bundle_dir, "Procfile")
        with open(path, "w") as f:
            f.write(content)

    def _write_main(self, bundle_dir: str,
                    app_name: str):
        """Write the entry point main.py for the bundle."""
        content = f'''#!/usr/bin/env python3
"""
NEKOVA App Bundle Entry Point
App: {app_name}
Generated by NEKOVA Compiler v1.0.0
"""
import sys
import os

# Add bundle root to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def load_env():
    env_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)), ".env")
    if os.path.exists(env_path):
        with open(env_path, "r") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    os.environ[key.strip()] = val.strip()

load_env()

from runner import NEKOVARunner

if __name__ == "__main__":
    filepath = sys.argv[1] if len(sys.argv) > 1 else "{app_name}.aion"
    runner   = NEKOVARunner(filepath=filepath)
    exit_code = runner.run()
    sys.exit(exit_code)
'''
        path = os.path.join(bundle_dir, "main.py")
        with open(path, "w") as f:
            f.write(content)

    def _write_readme(self, bundle_dir: str,
                      app_name: str):
        """Write README.md for the bundle."""
        content = f"""# {app_name} — NEKOVA App

Built with [NEKOVA Programming Language](https://github.com/kinghenesey/NEKOVA)

## Running Locally

```bash
pip install -r requirements.txt
python main.py {app_name}.aion
```

## Environment Variables

Create a `.env` file with:

## Deploying

See `deploy_instructions.txt` for cloud deployment options.
"""
        path = os.path.join(bundle_dir, "README.md")
        with open(path, "w") as f:
            f.write(content)

    def _write_railway_config(self, bundle_dir: str,
                               app_name: str):
        """Write railway.json config."""
        config = {
            "$schema": "https://railway.app/railway.schema.json",
            "build": {
                "builder": "NIXPACKS"
            },
            "deploy": {
                "startCommand": f"python main.py {app_name}.aion",
                "restartPolicyType": "ON_FAILURE",
                "restartPolicyMaxRetries": 10
            }
        }
        import json
        path = os.path.join(bundle_dir, "railway.json")
        with open(path, "w") as f:
            json.dump(config, f, indent=2)