#!/usr/bin/env python3
# ============================================================
# Compiled AION Program
# Generated by AION Compiler v1.0.0
# ============================================================
import os, sys, re, time, random

# ── AION Runtime ────────────────────────────────────────────

def _aion_show(value):
    """AION show statement."""
    if value is None:       print("null")
    elif value is True:     print("true")
    elif value is False:    print("false")
    else:                   print(str(value))

def _aion_think(prompt):
    """AION think statement — calls AI provider."""
    try:
        import sys, os
        sys.path.insert(0, os.path.dirname(__file__))
        from ai.providers import get_provider
        provider = get_provider()
        response = provider.ask(str(prompt))
        print(f"\033[96m🧠 {response}\033[0m")
        return response
    except Exception as e:
        print(f"[think error: {e}]")
        return ""

def _aion_interpolate(text, local_vars):
    """Handle string interpolation."""
    import re
    def replace(m):
        name = m.group(1)
        return str(local_vars.get(name, m.group(0)))
    return re.sub(r'\{(\w+)\}', replace, text)

def _aion_to_string(v):
    if v is None:   return "null"
    if v is True:   return "true"
    if v is False:  return "false"
    return str(v)

# ── Built-in functions ───────────────────────────────────────
def type_of(x):   return type(x).__name__
def to_number(x): return float(x) if "." in str(x) else int(x)
def to_text(x):   return str(x)
def length(x):    return len(x)
def ask(p=""):    return input(str(p))
def clear():      print("\033[H\033[J", end="")
def sleep(s=1):   time.sleep(float(s))
def random_num(a, b): return random.randint(int(a), int(b))

# ── Main Program ─────────────────────────────────────────────

name = _aion_interpolate('Emmanuel', locals())
age = 20
_aion_show(_aion_interpolate('Welcome to AION', locals()))
_aion_show((_aion_interpolate('Hello ', locals()) + name))
if (age >= 18):
    _aion_show(_aion_interpolate('You are an adult', locals()))
else:
    _aion_show(_aion_interpolate('You are a minor', locals()))
for _i in range(int(3)):
    _aion_show(_aion_interpolate('AION is alive!', locals()))